name: Run test jobs
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: plus3it/actions-workflows/.github/workflows/test.yml@ddd67e99878a285f728de398c1116151c2d7791a

  linux:
    uses: plus3it/actions-workflows/.github/workflows/test-salt-linux.yml@ddd67e99878a285f728de398c1116151c2d7791a
    strategy:
      matrix:
        os_version:
          - 8
          - 9
        salt_state:
          - postman-api
        salt_pillar_root:
          - ./tests/pillar/test-linux-main
    with:
      salt-os-version: ${{ matrix.os_version }}
      salt-state: ${{ matrix.salt_state }}
      salt-pillar-root: ${{ matrix.salt_pillar_root }}

  lint_powershell:
    name: PowerShell Linting
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path ./ -Include *.ps1 -Recurse
          Write-Host "--- Starting PowerShell Static Analysis ---"

          $anyErrors = $false

          foreach ($file in $files) {
              $relativePath = $file.FullName.Replace($PWD.ProviderPath, ".")
              $results = Invoke-ScriptAnalyzer -Path $file.FullName -Severity Warning

              if ($results) {
                  Write-Host "FAIL: $relativePath" -ForegroundColor Red
                  $results | Format-Table -AutoSize
                  $anyErrors = $true
              } else {
                  Write-Host "PASS: $relativePath" -ForegroundColor Green
              }
          }

          if ($anyErrors) {
              Write-Error "Static analysis failed. Please fix the errors above."
              exit 1
          } else {
              Write-Host "--- All files passed analysis! ---"
          }
